module.exports = {
	MONGODB_URI: process.env.MONGODB_URI,
	TWITTER_CONSUMER_KEY: process.env.TWITTER_CONSUMER_KEY,
	TWITTER_CONSUMER_SECRET: process.env.TWITTER_CONSUMER_SECRET,
  JWT_SECRET: process.env.JWT_SECRET,
  COOKIE_SECRET: process.env.COOKIE_SECRET,
  BASETRIP_SECRET:  process.env.BASETRIP_SECRET
};
