module.exports = {
  MONGO_URI: process.env.MONGO_URI,
	TWITTER_CONSUMER_KEY: process.env.TWITTER_CONSUMER_KEY,
	TWITTER_CONSUMER_SECRET: process.env.TWITTER_CONSUMER_SECRET,
	COOKIE_SECRET: process.env.COOKIE_SECRET
};
